<?php
/**
 * @category    Ledyer
 * @author      Oskars Elksnitis <info@scandiweb.com>
 * @package     Ledyer_Payment
 * @copyright   Copyright (c) 2022 Scandiweb, Ltd (https://scandiweb.com)
 */

/** @var \Ledyer\Payment\Block\Checkout\ToggleButtons $block */
?>
<script>
    window.ledyerConfig = {};
    <?php if ($block->isEnabled()): ?>
    window.ledyerConfig.b2cText = '<?= /* @noEscape */ $block->getB2CText() ?>';
    window.ledyerConfig.b2bText = '<?= /* @noEscape */ $block->getB2BText() ?>';
    window.ledyerConfig.b2cUrl = '<?= /* @noEscape */ $block->getB2CUrl() ?>';
    window.ledyerConfig.b2bUrl = '<?= /* @noEscape */ $block->getB2BUrl() ?>';
    <?php endif; ?>
</script>
